service: nextjs-hapi-lambda

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 1024
  timeout: 30
  skipCredentialsValidation: true
  
functions:
  app:
    handler: dist/server.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
      - http:
          path: /
          method: ANY

package:
  individually: true
  exclude:
    - ./**
  include:
    - dist/**
    - .next/**
    - public/**
    - node_modules/**

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002
    noPrependStageInUrl: true
    useChildProcesses: true